make:
	g++ -std=c++11  client.cpp -o peerclient -l boost_system

gen:
	g++ -std=c++11  coins.cpp -o gen -l boost_system

test:
	g++ -std=c++11  main.cpp -o coin -l boost_system


cleangen:
	rm gen
cleancoin:
	rm coin
cleanmain:
	rm peerclient